name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: merito_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/merito_test
      BRAPI_TOKEN: ${{ secrets.BRAPI_TOKEN }}
      PORT: 3333

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Rodar migrations
        run: npx prisma migrate deploy

      - name: Rodar testes
        run: npm test

      - name: Build da imagem Docker
        run: docker build -t merito_api .

      - name: Simulação de deploy
        run: echo "🚀 Deploy realizado com sucesso!"